import { getReport } from '@/app/actions';
import { AnalysisDashboard } from '@/components/analysis/analysis-dashboard';
import { notFound } from 'next/navigation';

import { VoteControl } from '@/components/analysis/vote-control';
import { DownloadReportButton } from '@/components/analysis/download-report-button';

export default async function ReportPage({ params }: { params: Promise<{ id: string }> }) {
    const { id } = await params;
    const report = await getReport(id);

    if (!report) {
        notFound();
    }

    return (
        <div className="min-h-screen bg-neutral-50 p-8 print:bg-white print:p-0">
            <div className="mx-auto max-w-4xl">
                <header className="mb-8 border-b border-neutral-200 pb-6 flex justify-between items-start print:hidden">
                    <div>
                        <h1 className="text-3xl font-bold text-neutral-900">Unearth Analysis Report</h1>
                        <p className="mt-2 text-neutral-600">
                            Verified analysis report generated by Unearth Agent.
                        </p>
                    </div>
                    <DownloadReportButton report={report} />
                </header>

                {/* Print-only header */}
                <header className="hidden print:block mb-8 border-b border-neutral-200 pb-6">
                    <h1 className="text-2xl font-bold text-neutral-900">Unearth Analysis Report</h1>
                    <p className="text-sm text-neutral-600">Generated on {new Date().toLocaleDateString()}</p>
                </header>

                <div className="rounded-xl bg-white p-6 shadow-sm ring-1 ring-neutral-200 print:shadow-none print:ring-0 print:p-0">
                    <AnalysisDashboard results={report} />

                    <div className="mt-8 border-t border-gray-100 pt-8">
                        <VoteControl reportId={id} initialVotes={report.votes} />
                    </div>
                </div>

                <footer className="mt-12 text-center text-sm text-neutral-500">
                    <p>Generated by Unearth. Verify before you trust.</p>
                </footer>
            </div>
        </div>
    );
}
